name: Postgres connection
on:
  workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: priyabrat
          POSTGRES_PASSWORD: Behera@2002
          POSTGRES_DB: Priyabrat
        ports:
          - 5432:5432


    steps:
      - name: show table
        run: |
#          psql -U ${{ job.services.postgres.env.POSTGRES_USER }} -d ${{ job.services.postgres.env.POSTGRES_DB }}
           psql -U priyabrat -d Priyabrat    
          \d