name: Postgres connection
on:
  workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: priyabrat
          POSTGRES_PASSWORD: Behera@2002
          POSTGRES_DB: Priyabrat
        ports:
          - 5432:5432
    steps:
      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize database with SQL file
        env:
          PGPASSWORD: Behera@2002
        run: |
           psql -h localhost -U priyabrat -d Priyabrat -v /Users/litanbehera/priyabrat_database_backup

      - name: Show tables
        env:
          PGPASSWORD: Behera@2002
        run: |
         psql -h localhost -U priyabrat -d Priyabrat -c "CREATE TABLE IF NOT EXISTS books1111 (id SERIAL PRIMARY KEY, title VARCHAR(100));"
         psql -h localhost -U priyabrat -d Priyabrat -c "INSERT INTO books1111 (title) VALUES ('Sample Book');"
         psql -h localhost -U priyabrat -d Priyabrat -c "SELECT * FROM books1111"
         
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Install PostgreSQL client
#        run: sudo apt-get install -y postgresql-client

#      - name: Restore database with pg_restore
#        env:
#          PGPASSWORD: Behera@2002
#        run: |
#          pg_restore -h localhost -U priyabrat -d Pri678yabrat -v scripts/database_dump.sql

      - name: Show tables
        env:
          PGPASSWORD: Behera@2002
        run: |
          psql -h localhost -U priyabrat -d Priyabrat -c "\d"
          
