name: Postgres connection
on:
  workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: priyabrat
          POSTGRES_PASSWORD: Behera@2002
          POSTGRES_DB: Priyabrat
        ports:
          - 5432:5432


    steps:
      - name: show table
        run: |
           psql -h localhost -U priyabrat -d Priyabrat    
           \d