name: Yml writing practice

on: workflow_dispatch

jobs:
  test:
    runs-on:
      - ubuntu-latest
    environment: production
    steps:
      - name: Print env first value
        run: |
          echo "Hello world!"
          echo "${{.github}}"

#  deploy:
#    needs: test
#    runs-on:
#      - ubuntu-latest
#    steps:
#      - name: Print env second value
#        run: |
#          echo "${{vars.LASTNAME}}"
#          echo "${{toJSON(github)}}"
