name: Yml writing practice

on: workflow_dispatch

env:
  kay: "value"
  key1: "value1"

jobs:
  test:
    runs-on:
      - self-hosted

    steps:
      - name: Print env first value
        run: |
          echo "Hello world!"
          echo "${{env.kay}}"
        

  deploy:
    needs: test
    runs-on:
      - self-hosted
    steps:
      - name: Print env second value
        run: |
          echo "Hello world!"
          echo "${{var.TESTNG_ANDROID_XMLFILE}}"