name: Floatr Project
on:
  workflow_dispatch:
    inputs:
      DEVICE_TYPE:
        description: 'Select the device type'
        required: true
        default: 'iOS'
        type: choice
        options:
          - "Android"
          - "iOS"
          - "Both in parallel"
      
      TEST_TYPE:
        description: 'Select the test type'
        required: true
        default: 'Smoke Test'
        type: choice
        options:
          - "Smoke Test"
          - "Regression Test"
          - "Validation Test"

      MODULE_NAME:
        description: 'Select the test type'
        required: true
        default: 'Smoke Test'
        type: choice
        options:
          - "Smoke Test"
          - "Regression Test"
          - "Validation Test"      
      
jobs:
  test:
    runs-on:
      - self-hosted
    env:
      MAVEN_OPTS: "--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED"

    steps:
        - name: Appium Tests
          uses: actions/checkout@v3

        - name: Cache Maven dependencies
          uses: actions/cache@v2
          with:
              path: ~/.m2/repository
              key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
              restore-keys: |
                ${{ runner.os }}-maven-

        - name: Verify APK file exists
          run: ls -l src/test/resources/Apps

        - name: List feature files
          run: find src/test/resources -name "*.feature"

        - name: Appium Tests
          run: |
            echo "Running tests on device type: ${{ github.event.inputs.DEVICE_TYPE }}"
            mvn test -Dsurefire.suiteXmlFiles=testng-android.xml -Dcucumber.filter.tags=@MutualFundRegression