name: Floatr Project
on:
  workflow_dispatch:
    inputs:
      DEVICE_TYPE:
        description: 'Select the device type'
        required: true
        default: 'iOS'
        type: choice
        options:
          - "Android"
          - "iOS"
          - "Both in parallel"

      TEST_TYPE:
        description: 'Select the test type'
        required: true
        default: 'Smoke Test'
        type: choice
        options:
          - "Smoke Test"
          - "Regression Test"
          - "Validation Test"

      MODULE_NAME:
        description: 'Select the test type'
        required: true
        default: 'Smoke Test'
        type: choice
        options:
          - "Smoke Test"
          - "Regression Test"
          - "Validation Test"

jobs:
  test:
    runs-on:
      - self-hosted
    env:
      MAVEN_OPTS: "--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED"

    steps:
        - name: Get code
          uses: actions/checkout@v3

        - name: Cache Maven dependencies
          uses: actions/cache@v2
          with:
              path: ~/.m2/repository
              key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
              restore-keys: |
                ${{ runner.os }}-maven-

        - name: Verify APK file exists
          run: ls -l src/test/resources/Apps

        - name: Check and Set APK Permissions
          run: chmod +r src/test/resources/Apps/app-release-25.apk

        - name: Verify APK Format
          run: file src/test/resources/Apps/app-release-25.apk

        - name: publish file
          run: |
            find test-output/*.png -type f -execdir echo '{}' ';'
            find src/test/resources/adminfeatures/*.feature -type f -execdir echo '{}' ';'

        - name: download image
          uses: actions/download-artifact@v3
          with:
            name: cucumber report
            path: test-output/*.png




#        - name: Run Appium Tests with Verbose Logs
##          run: mvn clean test -Dappium.server.logs -Dsurefire.suiteXmlFiles=${{ vars.TESTNG_ANDROID_XMLFIL }}
#          run: |
##            mvn test -Dsurefire.suiteXmlFiles=${{ vars.TESTNG }} -Dcucumber.filter.tags=@BudgetRegression
#             mvn clean test
#        - name: download artifact
#          uses: actions/upload-artifact@v4
#          with:
#            name: cucumber report
#            path: target/Pixel5
##        - name: Appium Tests
##          run: |
##            echo "Running tests on device type: ${{ github.event.inputs.DEVICE_TYPE }}"
##            mvn test -Dsurefire.suiteXmlFiles=testng-android.xml -Dcucumber.filter.tags=@MutualFundRegression

